stages:
  fetch_data:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - base.BASE_URL
    - base.EXPECTED_COLUMNS
    - base.GT_COLUMNS
    - base.N_LOCATIONS
    - base.YEAR
    - download.DOWNLOAD_PATH
    outs:
    - intermediate/
