stages:
  process:
    cmd: python src/process.py
    deps:
    - downloaded
    - src/process.py
    params:
    - base.EXPECTED_COLUMNS
    - base.YEAR
    - process.INPUT_PATH
    - process.OUTPUT_FILE_NAME
    - process.OUTPUT_PATH
    outs:
    - processed
  prepare:
    cmd: python src/prepare.py
    deps:
    - downloaded
    - src/prepare.py
    params:
    - base.GT_COLUMNS
    - prepare.INPUT_PATH
    - prepare.OUTPUT_FILE_NAME
    - prepare.OUTPUT_PATH
    outs:
    - prepared
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - prepared
    - processed
    - src/evaluate.py
    params:
    - base.MAPPING
    - evaluate.INPUT_FILE_NAMES
    - evaluate.INPUT_PATHS
    metrics:
    - eval/live/metrics.json:
        cache: false
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - base.BASE_URL
    - base.EXPECTED_COLUMNS
    - base.GT_COLUMNS
    - base.N_LOCATIONS
    - base.YEAR
    - download.DOWNLOAD_PATH
    - download.SEED
    outs:
    - downloaded
