base:
  BASE_URL: "https://www.ncei.noaa.gov/data/local-climatological-data/access/"
  YEAR: 2023
  N_LOCATIONS: 5
  EXPECTED_COLUMNS: ["HourlyDryBulbTemperature"]
  GT_COLUMNS: ["MonthlyMeanTemperature"]
  MAPPING:
    "HourlyDryBulbTemperature": "MonthlyMeanTemperature"

download:
  DOWNLOAD_PATH: "downloaded"
  SEED: 42

process:
  INPUT_PATH: "downloaded"
  OUTPUT_PATH: "processed"
  OUTPUT_FILE_NAME: "processed_averages.json"


prepare:
  INPUT_PATH: "downloaded"
  OUTPUT_PATH: "prepared"
  OUTPUT_FILE_NAME: "actual_averages.json"

evaluate:
  INPUT_PATHS: ["processed", "prepared"]
  OUTPUT_PATH: "eval"
  INPUT_FILE_NAMES: ["processed_averages.json","actual_averages.json"]

